### PR TITLE
Handle PHP 8.1 types in proxies

### LINKED ISSUE #948: Attempted to call an undefined method named "getName" of class "ReflectionIntersectionType"
Hi,

while playing around with php 8.1 on our symfony project I hit the mentioned exception while clearing the cache.

Tested version: doctrine/common 3.1.2 and 3.2.0

Steps to reproduce: type hint a one to many relation with `Collection&Selectable`
(use Doctrine\Common\Collections\Collection; use Doctrine\Common\Collections\Selectable;)

`{"message":"Uncaught Error: Call to undefined method ReflectionIntersectionType::getName()","context":{"exception":{"class":"Error","message":"Call to undefined method ReflectionIntersectionType::getName()","code":0,"file":"/var/www/project/htdocs/vendor/doctrine/common/lib/Doctrine/Common/Proxy/ProxyGenerator.php:1148"}},"level":500,"level_name":"CRITICAL","channel":"php","datetime":"2021-12-20T17:28:01.249423+00:00","extra":{}}
17:28:01 CRITICAL  [php] Uncaught Error: Call to undefined method ReflectionIntersectionType::getName() ["exception" => Error { …}]`

There is a condition to handle ReflectionUnionType in ProxyGenerator but indeed nothing which handles ReflectionIntersectionType.

Best regards,
Jeldrik

### PR DESCRIPTION
**Pull request by malarzm**
This allows using `never` and intersection types in proxied classes. Fixes #948

### CODE REVIEW

File: tests/Doctrine/Tests/Common/Util/DebugTest.php [hunk 1]
```diff
@@ -121,6 +121,8 @@ public function testDisablesOutput()
      * @param array<string, int> $expected
      *
      * @dataProvider provideAttributesCases
+     *
+     * @requires PHP < 8.1.0
```
Comment (malarzm) [inline tests/Doctrine/Tests/Common/Util/DebugTest.php:125]: Somehow PHP 8.1 changed return order of stuff that `Debug` is returning. Given `Debug` is deprecated I'm not going to invest time in fixing its tests for newer PHP versions.

<details>
<summary>For the record, test fails with:</summary>

```
1) Doctrine\Tests\Common\Util\DebugTest::testExportParentAttributes with data set "different-attributes" (Doctrine\Tests\Common\Util\TestAsset\ChildClass Object (...), array(4, 5, 6, 1, 2, 3))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '(
+    [childPublicAttribute] => 4
+    [childProtectedAttribute:protected] => 5
+    [childPrivateAttribute:Doctrine\Tests\Common\Util\TestAsset\ChildClass:private] => 6
     [parentPublicAttribute] => 1
     [parentProtectedAttribute:protected] => 2
     [parentPrivateAttribute:Doctrine\Tests\Common\Util\TestAsset\ParentClass:private] => 3
-    [childPublicAttribute] => 4
-    [childProtectedAttribute:protected] => 5
-    [childPrivateAttribute:Doctrine\Tests\Common\Util\TestAsset\ChildClass:private] => 6
 )
 '

/home/runner/work/common/common/tests/Doctrine/Tests/Common/Util/DebugTest.php:133

2) Doctrine\Tests\Common\Util\DebugTest::testExportParentAttributes with data set "same-attributes" (Doctrine\Tests\Common\Util\TestAsset\ChildWithSameAttributesClass Object (...), array(4, 5, 6, 3))
Failed asserting that two strings are identical.
--- Expected
+++ Actual
@@ @@
 '(
     [parentPublicAttribute] => 4
     [parentProtectedAttribute:protected] => 5
+    [parentPrivateAttribute:Doctrine\Tests\Common\Util\TestAsset\ChildWithSameAttributesClass:private] => 6
     [parentPrivateAttribute:Doctrine\Tests\Common\Util\TestAsset\ParentClass:private] => 3
-    [parentPrivateAttribute:Doctrine\Tests\Common\Util\TestAsset\ChildWithSameAttributesClass:private] => 6
 )
 '
```
</details>

Comment (derrabus) [reply tests/Doctrine/Tests/Common/Util/DebugTest.php:125]: PHP 8.1 changed the order in which class memebers appear if an object is cast to an array.

**Review by derrabus — APPROVED** [review]
