### PR TITLE
Use random_bytes instead of uniqid

### LINKED ISSUE #962: Proxy generator hangs indefinitely when system time is mocked
# Bug Report
Proxy generator hangs indefinitely when system time is mocked

Q | A
-- | --
BC Break | no
Version | 2.x/3.x

### Summary

Because `uniqid` relies on system time, when the clock is mocked (e.g. with libfaketime) and it does not advance, calling uniqid more than 1 times will hang up the process indefinitely. This means, when running tests with mocked constant time, the code gets stuck at https://github.com/doctrine/common/blob/c824e95d4c83b7102d8bc60595445a6f7d540f96/lib/Doctrine/Common/Proxy/ProxyGenerator.php#L341

---

### How to reproduce the issue with plain`uniqid`:

```bash
docker build -t php-faketime - <<DOCKERFILE
FROM php:8.1-cli
RUN apt-get update && apt-get install -y libfaketime   
ENV LD_PRELOAD=/usr/lib/x86_64-linux-gnu/faketime/libfaketime.so.1
DOCKERFILE

docker run --rm -e FAKETIME="2000-02-02 02:02:02" php-faketime -r 'echo uniqid(), PHP_EOL, uniqid();'
``` 

Ideally this would be patched in PHP but I think that won't happen since even the [docs](https://www.php.net/manual/en/function.uniqid.php) mention that `uniqid` is using microtime as random seed, so this is probably considered as a feature and not a bug.

### Possible solutions
I think it would be better to use something like [`tempnam`](https://www.php.net/manual/en/function.tempnam.php), or some other time-independent random function.

---

Related discussion in [libfaketime repository](https://github.com/wolfcw/libfaketime/issues/349).

### PR DESCRIPTION
**Pull request by valtzu**
Closes #962

### CODE REVIEW

File: lib/Doctrine/Common/Proxy/ProxyGenerator.php [hunk 1]
```diff
@@ -338,7 +339,8 @@ public function generateProxyClass(ClassMetadata $class, $fileName = false)
             throw UnexpectedValueException::proxyDirectoryNotWritable($this->proxyDirectory);
         }
 
-        $tmpFileName = $fileName . '.' . uniqid('', true);
+        /** @noinspection PhpUnhandledExceptionInspection */
```
Comment (greg0ire) [inline lib/Doctrine/Common/Proxy/ProxyGenerator.php]: No IDE-specific stuff please 🙏

Comment (valtzu) [reply lib/Doctrine/Common/Proxy/ProxyGenerator.php]: Ok, sorry, removed.

**Review by greg0ire — APPROVED** [review]
Maintainers : to be squash merged

**Review by derrabus — APPROVED** [review]
